
# for flashing : press boot button for 2-3 seconds before the serial connection initialize
# After OTA update, the EN (reset) button must be pressed to run firmware
# do not use gpio12 (MTDI)

##### temporary fix to use new adc library (https://github.com/esphome/issues/issues/6455)
external_components:
  - source: github://pr#9021 #https://github.com/esphome/esphome/pull/9021
    refresh: 30s
    components:
      - adc

############## General configuration

substitutions:
  name: floor-heating-controller #no special caracters
  friendly_name: "Floor heating"
  id_prefix: "heating_controller_" #if you have more than one board, it could be usefull to remane all the "id:heating_controller_xxxx" with a decicaded prefix [not done in sensor_adc.yaml actually]
  revision: "1.123"
    
  #time
  TZ: "Europe/Zurich" #timezone
  reboot_days_of_week: "MON"
  reboot_hours: "5"
  reboot_minutes: "0"
  reboot_seconds: "0"
  # valve_maintenance_interval: "7days"
  onboot_valve_calibration_delay: "1min"
  
  dallasaddress_input: "0xb300000084aa6128"
  dallasaddress_output: "0xeb0000008492ad28"
  
  adc_zero_calibration: "-0.075" #typical : -0.075 for esp32 devkit, 0.005 for esp32-c3. + motor eventual specific inpedance
  pump_mac_address: "AA:BB:CC:DD:EE:FF"
  
web_server:
  port: 80
  version: 3
  # sorting_groups:
    # - id: sorting_group_climate
      # name: "Climate"
      # sorting_weight: 1
    # - id: sorting_group_sensors
      # name: "Sensors"
      # sorting_weight: 2
    # - id: sorting_group_actions
      # name: "Actions"
      # sorting_weight: 3
    # - id: sorting_group_covers
      # name: "Manual covers"
      # sorting_weight: 40
    # - id: sorting_group_BEMF
      # name: "Debug : BEMF"
      # sorting_weight: 50
    # - id: sorting_group_inputs
      # name: "Debug : inputs"
      # sorting_weight: 60
  log: true
  # local: false #true in case of no internet
  
# Enable HOME Assistant API
api:
  reboot_timeout: 30min

  
############## Channels definition (packages as template : https://espHOME.io/guides/configuration-types.html#packages-as-templates)
packages:
##### Sample Pump controll via ESP Now

  pump_control: !include
      file: pump_control.yaml
      vars:
        pump_mac_address: ${pump_mac_address}
        circulation_check_interval: "24h"
        circulation_run_duration: "5min"

##### Sample PID config
  # channel_1: !include
    # file: heating_channel_PID.yaml
    # vars:
      # channel_number: 1
      # id: wc #bad
      # frendly_name: wc #bad
      # temperature_sensor: corridor_temperature_sensor
      # default_target_temperature_low: "21 °C"
      # pid_kp: "0.06"
      # pid_ki: "0.00011"
      # pid_kd: "4.0"
      # visual_min_temperature: "10 °C"
      # visual_max_temperature: "30 °C"
      # visual_temperature_step: "0.1 °C"
      # bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      ### do not change : 
      # bemf_sensor_adc: BEMF_1_2_sensor_ADC
      # bemf_linked_with_channel: 2
      # sn74hc595_IA_pin: 0
      # sn74hc595_IB_pin: 1
 
##### Sample linear config 
  # channel_2: !include
    # file: heating_channel_linear.yaml
    # vars:
      # channel_number: 2
      # id: storage
      # frendly_name: storage
      # temperature_sensor: reduit_temperature_sensor
      # default_preset: HOME
      # preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      # preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      # preset_1_target_temperature_low: "19 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      # preset_2_name: AWAY 
      # preset_2_mode: HEAT
      # preset_2_target_temperature_low: "18 °C"
      # preset_2_target_temperature_high: "19 °C"
      # preset_3_name: BOOST 
      # preset_3_mode: HEAT
      # preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      # visual_min_temperature: "10 °C"
      # visual_max_temperature: "30 °C"
      # visual_temperature_step: "0.1 °C"
      # check_interval: "16min"
      # bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      # do not change : 
      # bemf_sensor_adc: BEMF_1_2_sensor_ADC
      # bemf_linked_with_channel: 1
      # sn74hc595_IA_pin: 2
      # sn74hc595_IB_pin: 3
      
##### Sample tanh (non linear) config 
  # channel_1: !include
    # file: heating_channel_tanh.yaml
    # vars:
      # channel_number: 1
      # id: wc
      # frendly_name: wc
      # temperature_sensor: corridor_temperature_sensor #must match one sensor defined in sensor_temperature.yaml
      # default_preset: HOME
      # preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      # preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      # preset_1_target_temperature_low: "19 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      # preset_2_name: AWAY 
      # preset_2_mode: HEAT
      # preset_2_target_temperature_low: "18 °C"
      # preset_2_target_temperature_high: "19 °C"
      # preset_3_name: BOOST 
      # preset_3_mode: HEAT
      # preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      # visual_min_temperature: "10 °C"
      # visual_max_temperature: "30 °C"
      # visual_temperature_step: "0.1 °C"
      # check_interval: "15min"
      # bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      # tanh_steepness: "0.70" ############# NEW
      # #do not change : 
      # bemf_sensor_adc: BEMF_1_2_sensor_ADC
      # bemf_linked_with_channel: 2
      # sn74hc595_IA_pin: 0
      # sn74hc595_IB_pin: 1
      
##### Sample fully remote controlled channel config 
  # channel_1: !include
    # file: heating_channel_remote_controlled.yaml
    # vars:
      # channel_number: 1
      # id: wc
      # frendly_name: wc
      # temperature_sensor: corridor_temperature_sensor #must match one sensor defined in sensor_temperature.yaml
      # default_preset: HOME
      # preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      # preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      # preset_1_target_temperature_low: "19 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      # preset_2_name: AWAY 
      # preset_2_mode: HEAT
      # preset_2_target_temperature_low: "18 °C"
      # preset_2_target_temperature_high: "19 °C"
      # preset_3_name: BOOST 
      # preset_3_mode: HEAT
      # preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      # visual_min_temperature: "10 °C"
      # visual_max_temperature: "30 °C"
      # visual_temperature_step: "0.1 °C"
      # #check_interval: "15min"
      # bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      # #tanh_steepness: "0.70" ### new parameter for heating_channel_tanh.yaml only
      # #do not change : 
      # bemf_sensor_adc: BEMF_1_2_sensor_ADC
      # bemf_linked_with_channel: 2
      # sn74hc595_IA_pin: 0
      # sn74hc595_IB_pin: 1

#### normal channel config
  channel_1: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 1
      id: wc
      frendly_name: wc
      temperature_sensor: corridor_temperature_sensor #must match one sensor defined in sensor_temperature.yaml
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "19 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "15min"
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70" ### new parameter for heating_channel_tanh.yaml only
      # do not change : 
      bemf_sensor_adc: BEMF_1_2_sensor_ADC
      bemf_linked_with_channel: 2
      sn74hc595_IA_pin: 0
      sn74hc595_IB_pin: 1
      
      

  channel_2: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 2
      id: storage
      frendly_name: storage
      temperature_sensor: reduit_temperature_sensor
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "19 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "16min"
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70"
      ## do not change : 
      bemf_sensor_adc: BEMF_1_2_sensor_ADC
      bemf_linked_with_channel: 1
      sn74hc595_IA_pin: 2
      sn74hc595_IB_pin: 3
      

      
  channel_3: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 3
      id: living
      frendly_name: living
      temperature_sensor: living_room_temperature_sensor
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "19 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "17min"
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70"
      ## do not change :
      bemf_sensor_adc: BEMF_3_4_sensor_ADC
      bemf_linked_with_channel: 4
      sn74hc595_IA_pin: 4
      sn74hc595_IB_pin: 5
      
      
  channel_4: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 4
      id: dining
      frendly_name: dining
      temperature_sensor: living_room_temperature_sensor #indoor_temperature_sensor
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "19 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "18min"  
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70"
      ## do not change :
      bemf_sensor_adc: BEMF_3_4_sensor_ADC
      bemf_linked_with_channel: 3
      sn74hc595_IA_pin: 6
      sn74hc595_IB_pin: 7
        
 
  channel_5: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 5
      id: kitchen
      frendly_name: kitchen
      temperature_sensor: living_room_temperature_sensor
      # default_target_temperature_low: "21 °C"
      # pid_kp: "0.06"
      # pid_ki: "0.00011"
      # pid_kd: "4.0"
      # visual_min_temperature: "10 °C"
      # visual_max_temperature: "30 °C"
      # visual_temperature_step: "0.1 °C"
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "19 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "15min"
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70"
      ## do not change :
      bemf_sensor_adc: BEMF_5_6_sensor_ADC
      bemf_linked_with_channel: 6
      sn74hc595_IA_pin: 8
      sn74hc595_IB_pin: 9
           
      
      
  channel_6: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 6
      id: office
      frendly_name: office
      temperature_sensor: office_temperature_sensor
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "21 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "19 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "23 °C"
      # preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "16min"
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70"
      ## do not change :
      bemf_sensor_adc: BEMF_5_6_sensor_ADC
      bemf_linked_with_channel: 5
      sn74hc595_IA_pin: 10
      sn74hc595_IB_pin: 11
      
      
  channel_7: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 7
      id: bedroom
      frendly_name: bedroom
      temperature_sensor: bedroom_temperature_sensor
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "18 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "20 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "18 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "19 °C"
      # preset_3_target_temperature_high: "24 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "17min"
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70"
      ## do not change :
      bemf_sensor_adc: BEMF_7_8_sensor_ADC
      bemf_linked_with_channel: 8
      sn74hc595_IA_pin: 12
      sn74hc595_IB_pin: 13
         
      
  channel_8: !include
    file: heating_channel_tanh.yaml
    vars:
      channel_number: 8
      id: bathroom
      frendly_name: bathroom
      temperature_sensor: bathroom_temperature_sensor
      default_preset: HOME
      preset_1_name: HOME #ECO, AWAY, BOOST, COMFORT, HOME, SLEEP, ACTIVITY
      preset_1_mode: HEAT #OFF, AUTO, HEAT, COOL, HEAT, FAN_ONLY, DRY
      preset_1_target_temperature_low: "22 °C" #ASHRAE studies recommend 21°C with a band of 2°C which result in 90% occupant acceptability
      # preset_1_target_temperature_high: "24 °C"
      preset_2_name: AWAY 
      preset_2_mode: HEAT
      preset_2_target_temperature_low: "20 °C"
      # preset_2_target_temperature_high: "19 °C"
      preset_3_name: BOOST 
      preset_3_mode: HEAT
      preset_3_target_temperature_low: "24 °C"
      # preset_3_target_temperature_high: "25 °C"
      visual_min_temperature: "10 °C"
      visual_max_temperature: "30 °C"
      visual_temperature_step: "0.1 °C"
      check_interval: "18min"
      bemf_trigger_initial_value: "0.650" # 0.105 for boards < v60 | 0.650 for boards >=v61
      tanh_steepness: "0.70"
      ## do not change :
      bemf_sensor_adc: BEMF_7_8_sensor_ADC
      bemf_linked_with_channel: 7
      sn74hc595_IA_pin: 14
      sn74hc595_IB_pin: 15
         




  
  board: !include board_esp32.yaml
  # board: !include board_esp32-C3.yaml
  logger: !include logger.yaml
  sn74hc595: !include sn74hc595.yaml
  wifi: !include wifi.yaml
  time: !include time.yaml
  script_calibrate_valves: !include script_calibrate_valves.yaml
  switch_others: !include switch_others.yaml
  inputs: !include inputs.yaml
  sensor_adc: !include sensor_adc.yaml
  sensor_temperature: !include sensor_temperature.yaml
  sensor_others: !include sensor_others.yaml
  onwire: !include onewire.yaml #only for boards >= rev 61

